/*
 * @StartMenu.java 1.1 2018/05/04
 *
 * Copyright (c) 2018 Aberystwyth University.
 * All rights reserved.
 *
 */
package uk.ac.aber.cs221.aumgroup.gameFrames;

import java.awt.*;
import java.awt.event.*;

/**
 * The StartMenu implements the start menu with all of
 its options
 * @author dkm4, jty, the12
 * @version 1.0 initial development
 * @version 1.1 added handlers for user interaction and updated references to main class (dkm4)
 */
public class StartMenu extends javax.swing.JFrame {
	
	private GameMainClass main;
	
    /**
     * Creates new form startMenu
     */
    public StartMenu() {
        initComponents();
		main = new GameMainClass();
		main.setStartMenu(this);
    }
    
	/**
	 * This method closes the window
	 */
     public void close(){
		WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
		Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbnewGame = new javax.swing.JButton();
        jbLoadGame = new javax.swing.JButton();
        jbhelp = new javax.swing.JButton();
        jbScoreBoard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Game Menu"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 221, 255));

        jbnewGame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbnewGame.setText("New Game");
        jbnewGame.setBorderPainted(false);
        jbnewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnewGameActionPerformed(evt);
            }
        });

        jbLoadGame.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbLoadGame.setText("Load Game");
        jbLoadGame.setBorderPainted(false);
        jbLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLoadGameActionPerformed(evt);
            }
        });

        jbhelp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbhelp.setText("Help");
        jbhelp.setBorderPainted(false);
        jbhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhelpActionPerformed(evt);
            }
        });

        jbScoreBoard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbScoreBoard.setText("Score Board");
        jbScoreBoard.setBorderPainted(false);
        jbScoreBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbScoreBoardActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/ac/aber/cs221/aumgroup/gameIcons/logo1Joggle2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbhelp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbScoreBoard))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbnewGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jbnewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbScoreBoard)
                    .addComponent(jbhelp))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * This method is called when the "new game" button is pressed
	 * It closes the window and displays a frame where the game is played
	 * @param evt the event being listened for 
	 */
    private void jbnewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnewGameActionPerformed
        close();
		main.showPlayGame();
    }//GEN-LAST:event_jbnewGameActionPerformed

	/**
	 * This method is called when the "help" button is pressed
	 * It displays the frame showing the game help
	 * @param evt the event being listened for 
	 */
    private void jbhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhelpActionPerformed
        // call the help frame
		main.showGameHelp();
    }//GEN-LAST:event_jbhelpActionPerformed

	/**
	 * This method is called when the "score board" button is pressed
	 * It displays the frame showing the score board
	 * @param evt the event being listened for 
	 */
    private void jbScoreBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbScoreBoardActionPerformed
        // call the score board frame
		main.showGameScoreBoard();
    }//GEN-LAST:event_jbScoreBoardActionPerformed

	/**
	 * This method is called when the "load game" button is pressed
	 * It displays a menu where the user selects the game to be loaded
	 * and then opens the game in a new window before closing this one
	 * @param evt the event being listened for 
	 */
    private void jbLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLoadGameActionPerformed
		main.showSelectGame();
    }//GEN-LAST:event_jbLoadGameActionPerformed

    /**
     * The main class set the nimbus and displays the form of the start menu
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbLoadGame;
    private javax.swing.JButton jbScoreBoard;
    private javax.swing.JButton jbhelp;
    private javax.swing.JButton jbnewGame;
    // End of variables declaration//GEN-END:variables
}
