/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameFrames;

import raw.commit.*;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author MY PC
 */
public class playGame extends javax.swing.JFrame {

    /**
     * Creates new form playGame
     */
    public playGame() {
        initComponents();
        populateGrids();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        countdownIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        clearWordBtn = new javax.swing.JButton();
        addWordBtn = new javax.swing.JButton();
        currentWordField = new javax.swing.JTextField();
        changeViewBtn = new javax.swing.JButton();
        grid1 = new Grid();
        g1R0C0 = new Tile(grid1, new PositionInGrid(0, 0));
        g1R0C1 = new Tile(grid1, new PositionInGrid(0, 1));
        g1R0C2 = new Tile(grid1, new PositionInGrid(0, 2));
        g1R1C2 = new Tile(grid1, new PositionInGrid(1, 2));
        g1R1C1 = new Tile(grid1, new PositionInGrid(1, 1));
        g1R1C0 = new Tile(grid1, new PositionInGrid(1, 0));
        g1R2C0 = new Tile(grid1, new PositionInGrid(2, 0));
        g1R2C1 = new Tile(grid1, new PositionInGrid(2, 1));
        g1R2C2 = new Tile(grid1, new PositionInGrid(2, 2));
        grid2 = new Grid();
        g2R0C0 = new Tile(grid2, new PositionInGrid(0, 0));
        g2R0C1 = new Tile(grid2, new PositionInGrid(0, 1));
        g2R0C2 = new Tile(grid2, new PositionInGrid(0, 2));
        g2R1C2 = new Tile(grid2, new PositionInGrid(1, 2));
        g2R1C1 = new Tile(grid2, new PositionInGrid(1, 1));
        g2R1C0 = new Tile(grid2, new PositionInGrid(1, 0));
        g2R2C0 = new Tile(grid2, new PositionInGrid(2, 0));
        g2R2C1 = new Tile(grid2, new PositionInGrid(2, 1));
        g2R2C2 = new Tile(grid2, new PositionInGrid(2, 2));
        grid3 = new Grid();
        g3R0C0 = new Tile(grid3, new PositionInGrid(0, 0));
        g3R0C1 = new Tile(grid3, new PositionInGrid(0, 1));
        g3R0C2 = new Tile(grid3, new PositionInGrid(0, 2));
        g3R1C2 = new Tile(grid3, new PositionInGrid(1, 2));
        g3R1C1 = new Tile(grid3, new PositionInGrid(1, 1));
        g3R1C0 = new Tile(grid3, new PositionInGrid(1, 0));
        g3R2C0 = new Tile(grid3, new PositionInGrid(2, 0));
        g3R2C1 = new Tile(grid3, new PositionInGrid(2, 1));
        g3R2C2 = new Tile(grid3, new PositionInGrid(2, 2));
        jTextField2 = new javax.swing.JTextField();
        scoreIcon = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Game Play"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 221, 255));

        countdownIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameIcons/Programming-Watch-icon.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CORRECT WORDS");

        jPanel7.setBackground(new java.awt.Color(0, 204, 255));

        clearWordBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clearWordBtn.setText("Clear Word");

        addWordBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addWordBtn.setText("Add word");

        currentWordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        currentWordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(currentWordField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(clearWordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addWordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentWordField)
                                        .addComponent(addWordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(clearWordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        changeViewBtn.setText("Change View");

        grid1.setBackground(new java.awt.Color(45, 221, 255));
        grid1.setGridNo(1);

        g1R0C0.setBackground(new java.awt.Color(255, 255, 255));
        g1R0C0.setText("A");
        g1R0C0.assignLetter(new Letter(LetterEnum.A));
        g1R0C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R0C0.setName("g1R0C0"); // NOI18N
        g1R0C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R0C1.setBackground(new java.awt.Color(255, 255, 255));
        g1R0C1.setText("Q");
        g1R0C1.assignLetter(new Letter(LetterEnum.Qu));
        g1R0C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R0C1.setName("g1R0C1"); // NOI18N
        g1R0C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R0C2.setBackground(new java.awt.Color(255, 255, 255));
        g1R0C2.setText("W");
        g1R0C2.assignLetter(new Letter(LetterEnum.W));
        g1R0C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R0C2.setName("g1R0C2"); // NOI18N
        g1R0C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R1C2.setBackground(new java.awt.Color(255, 255, 255));
        g1R1C2.setText("M");
        g1R1C2.assignLetter(new Letter(LetterEnum.M));
        g1R1C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R1C2.setName("g1R1C2"); // NOI18N
        g1R1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R1C1.setBackground(new java.awt.Color(255, 255, 255));
        g1R1C1.setText("D");
        g1R1C1.assignLetter(new Letter(LetterEnum.D));
        g1R1C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R1C1.setName("g1R1C1"); // NOI18N
        g1R1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R1C0.setBackground(new java.awt.Color(255, 255, 255));
        g1R1C0.setText("V");
        g1R1C0.assignLetter(new Letter(LetterEnum.V));
        g1R1C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R1C0.setName("g1R1C0"); // NOI18N
        g1R1C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R2C0.setBackground(new java.awt.Color(255, 255, 255));
        g1R2C0.setText("S");
        g1R2C0.assignLetter(new Letter(LetterEnum.S));
        g1R2C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R2C0.setName("g1R2C0"); // NOI18N
        g1R2C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R2C1.setBackground(new java.awt.Color(255, 255, 255));
        g1R2C1.setText("A");
        g1R2C1.assignLetter(new Letter(LetterEnum.A));
        g1R2C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R2C1.setName("g1R2C1"); // NOI18N
        g1R2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g1R2C2.setBackground(new java.awt.Color(255, 255, 255));
        g1R2C2.setText("W");
        g1R2C2.assignLetter(new Letter(LetterEnum.W));
        g1R2C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g1R2C2.setName("g1R2C2"); // NOI18N
        g1R2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        javax.swing.GroupLayout grid1Layout = new javax.swing.GroupLayout(grid1);
        grid1.setLayout(grid1Layout);
        grid1Layout.setHorizontalGroup(
                grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(grid1Layout.createSequentialGroup()
                                                        .addComponent(g1R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(g1R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g1R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(grid1Layout.createSequentialGroup()
                                                        .addComponent(g1R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g1R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g1R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(grid1Layout.createSequentialGroup()
                                                .addComponent(g1R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g1R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g1R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grid1Layout.setVerticalGroup(
                grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g1R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g1R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g1R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g1R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        grid1Tiles = new Tile[] { g1R0C0, g1R0C1, g1R0C2, g1R1C0, g1R1C1, g1R1C2, g1R2C0, g1R2C1, g1R2C2 };
        grid1.setAllTiles(grid1Tiles);

        grid2.setBackground(new java.awt.Color(45, 221, 255));
        grid2.setGridNo(2);

        g2R0C0.setBackground(new java.awt.Color(255, 255, 255));
        g2R0C0.setText("A");
        g2R0C0.assignLetter(new Letter(LetterEnum.A));
        g2R0C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R0C0.setName("g2R0C0"); // NOI18N
        g2R0C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R0C1.setBackground(new java.awt.Color(255, 255, 255));
        g2R0C1.setText("Qu");
        g2R0C1.assignLetter(new Letter(LetterEnum.Qu));
        g2R0C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R0C1.setName("g2R0C1"); // NOI18N
        g2R0C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R0C2.setBackground(new java.awt.Color(255, 255, 255));
        g2R0C2.setText("W");
        g2R0C2.assignLetter(new Letter(LetterEnum.W));
        g2R0C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R0C2.setName("g2R0C2"); // NOI18N
        g2R0C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R1C2.setBackground(new java.awt.Color(255, 255, 255));
        g2R1C2.setText("M");
        g2R1C2.assignLetter(new Letter(LetterEnum.M));
        g2R1C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R1C2.setName("g2R1C2"); // NOI18N
        g2R1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R1C1.setBackground(new java.awt.Color(255, 255, 255));
        g2R1C1.setText("D");
        g2R1C1.assignLetter(new Letter(LetterEnum.D));
        g2R1C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R1C1.setName("g2R1C1"); // NOI18N
        g2R1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R1C0.setBackground(new java.awt.Color(255, 255, 255));
        g2R1C0.setText("V");
        g2R1C0.assignLetter(new Letter(LetterEnum.V));
        g2R1C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R1C0.setName("g2R1C0"); // NOI18N
        g2R1C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R2C0.setBackground(new java.awt.Color(255, 255, 255));
        g2R2C0.setText("S");
        g2R2C0.assignLetter(new Letter(LetterEnum.S));
        g2R2C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R2C0.setName("g2R2C0"); // NOI18N
        g2R2C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R2C1.setBackground(new java.awt.Color(255, 255, 255));
        g2R2C1.setText("A");
        g2R2C1.assignLetter(new Letter(LetterEnum.A));
        g2R2C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R2C1.setName("g2R2C1"); // NOI18N
        g2R2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g2R2C2.setBackground(new java.awt.Color(255, 255, 255));
        g2R2C2.setText("W");
        g2R2C2.assignLetter(new Letter(LetterEnum.W));
        g2R2C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g2R2C2.setName("g2R2C2"); // NOI18N
        g2R2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        javax.swing.GroupLayout grid2Layout = new javax.swing.GroupLayout(grid2);
        grid2.setLayout(grid2Layout);
        grid2Layout.setHorizontalGroup(
                grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(grid2Layout.createSequentialGroup()
                                                        .addComponent(g2R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(g2R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g2R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(grid2Layout.createSequentialGroup()
                                                        .addComponent(g2R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g2R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g2R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(grid2Layout.createSequentialGroup()
                                                .addComponent(g2R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g2R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g2R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grid2Layout.setVerticalGroup(
                grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g2R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g2R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g2R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g2R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        grid3.setBackground(new java.awt.Color(45, 221, 255));
        grid3.setGridNo(3);

        g3R0C0.setBackground(new java.awt.Color(255, 255, 255));
        g3R0C0.setText("A");
        g3R0C0.assignLetter(new Letter(LetterEnum.A));
        g3R0C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R0C0.setName("g3R0C0"); // NOI18N
        g3R0C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R0C1.setBackground(new java.awt.Color(255, 255, 255));
        g3R0C1.setText("Qu");
        g3R0C1.assignLetter(new Letter(LetterEnum.Qu));
        g3R0C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R0C1.setName("g3R0C1"); // NOI18N
        g3R0C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R0C2.setBackground(new java.awt.Color(255, 255, 255));
        g3R0C2.setText("W");
        g3R0C2.assignLetter(new Letter(LetterEnum.W));
        g3R0C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R0C2.setName("g3R0C2"); // NOI18N
        g3R0C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R1C2.setBackground(new java.awt.Color(255, 255, 255));
        g3R1C2.setText("M");
        g3R1C2.assignLetter(new Letter(LetterEnum.M));
        g3R1C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R1C2.setName("g3R1C2"); // NOI18N
        g3R1C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R1C1.setBackground(new java.awt.Color(255, 255, 255));
        g3R1C1.setText("D");
        g3R1C1.assignLetter(new Letter(LetterEnum.D));
        g3R1C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R1C1.setName("g3R1C1"); // NOI18N
        g3R1C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R1C0.setBackground(new java.awt.Color(255, 255, 255));
        g3R1C0.setText("V");
        g3R1C0.assignLetter(new Letter(LetterEnum.V));
        g3R1C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R1C0.setName("g3R1C0"); // NOI18N
        g3R1C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R2C0.setBackground(new java.awt.Color(255, 255, 255));
        g3R2C0.setText("S");
        g3R2C0.assignLetter(new Letter(LetterEnum.S));
        g3R2C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R2C0.setName("g3R2C0"); // NOI18N
        g3R2C0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R2C1.setBackground(new java.awt.Color(255, 255, 255));
        g3R2C1.setText("A");
        g3R2C1.assignLetter(new Letter(LetterEnum.A));
        g3R2C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R2C1.setName("g3R2C1"); // NOI18N
        g3R2C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        g3R2C2.setBackground(new java.awt.Color(255, 255, 255));
        g3R2C2.setText("W");
        g3R2C2.assignLetter(new Letter(LetterEnum.W));
        g3R2C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        g3R2C2.setName("g3R2C2"); // NOI18N
        g3R2C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                someShit(evt);
            }
        });

        javax.swing.GroupLayout grid3Layout = new javax.swing.GroupLayout(grid3);
        grid3.setLayout(grid3Layout);
        grid3Layout.setHorizontalGroup(
                grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(grid3Layout.createSequentialGroup()
                                                        .addComponent(g3R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(g3R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g3R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(grid3Layout.createSequentialGroup()
                                                        .addComponent(g3R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g3R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(g3R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(grid3Layout.createSequentialGroup()
                                                .addComponent(g3R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g3R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(g3R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        grid3Layout.setVerticalGroup(
                grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(grid3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g3R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g3R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(g3R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(g3R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(312, 312, 312)
                                                                .addComponent(changeViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(grid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(grid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 13, Short.MAX_VALUE))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(changeViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(75, 75, 75)
                                                                                .addComponent(grid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(grid3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(36, 36, 36)))))
                                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        scoreIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameIcons/favourites-star-SH-icon.png"))); // NOI18N

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(countdownIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scoreIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(countdownIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField2))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(scoreIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        countdownIcon.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void someShit(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        Tile tile = (Tile) evt.getSource();
        Grid parent = (Grid) tile.getParent();
        if (parent == grid1) {
            grid1.handleTileAction(evt);
        } else if (parent == grid2) {
            grid2.handleTileAction(evt);
        } else if (parent == grid3) {
            grid3.handleTileAction(evt);
        }

    }

    private void populateGrids() {
        grid1.generateRandomLetters();
        grid1.populateGrid();


    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify
    private javax.swing.JButton addWordBtn;
    private javax.swing.JButton changeViewBtn;
    private javax.swing.JButton clearWordBtn;
    private javax.swing.JLabel countdownIcon;
    private javax.swing.JTextField currentWordField;
    private Tile g1R0C0;
    private Tile g1R0C1;
    private Tile g1R0C2;
    private Tile g1R1C0;
    private Tile g1R1C1;
    private Tile g1R1C2;
    private Tile g1R2C0;
    private Tile g1R2C1;
    private Tile g1R2C2;
    private Tile g2R0C0;
    private Tile g2R0C1;
    private Tile g2R0C2;
    private Tile g2R1C0;
    private Tile g2R1C1;
    private Tile g2R1C2;
    private Tile g2R2C0;
    private Tile g2R2C1;
    private Tile g2R2C2;
    private Tile g3R0C0;
    private Tile g3R0C1;
    private Tile g3R0C2;
    private Tile g3R1C0;
    private Tile g3R1C1;
    private Tile g3R1C2;
    private Tile g3R2C0;
    private Tile g3R2C1;
    private Tile g3R2C2;
    private Grid grid1;
    private Grid grid2;
    private Grid grid3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel scoreIcon;
    private Tile[] grid1Tiles;
    private Tile[] grid2Tiles;
    private Tile[] grid3Tiles;
    // End of variables declaration



//    // Variables declaration - do not modify
////    private javax.swing.JButton g1R0C0;
////    private javax.swing.JButton g1R0C1;
////    private javax.swing.JButton g1R0C2;
////    private javax.swing.JButton g1R1C0;
////    private javax.swing.JButton g1R1C1;
////    private javax.swing.JButton g1R1C2;
////    private javax.swing.JButton g1R2C0;
////    private javax.swing.JButton g1R2C1;
////    private javax.swing.JButton g1R2C2;
////    private javax.swing.JPanel grid1Panel;
//    private javax.swing.JPanel grid2Panel;
//    private javax.swing.JPanel grid3Panel;
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton13;
//    private javax.swing.JButton jButton14;
//    private javax.swing.JButton jButton15;
//    private javax.swing.JButton jButton16;
//    private javax.swing.JButton jButton17;
//    private javax.swing.JButton jButton18;
//    private javax.swing.JButton jButton19;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton20;
//    private javax.swing.JButton jButton21;
//    private javax.swing.JButton jButton22;
//    private javax.swing.JButton jButton23;
//    private javax.swing.JButton jButton24;
//    private javax.swing.JButton jButton25;
//    private javax.swing.JButton jButton26;
//    private javax.swing.JButton jButton27;
//    private javax.swing.JButton jButton28;
//    private javax.swing.JButton jButton29;
//    private javax.swing.JButton jButton30;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JList<String> jList1;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTextField jTextField1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JTextField jTextField3;
//    // End of variables declaration
//
//    // this is a 2D array containing all the buttons for grid 1
////    private JButton[][] grid1 = {{g1R0C0, g1R0C1, g1R0C2}, {g1R1C0, g1R1C1, g1R1C2}, {g1R2C0, g1R2C1, g1R2C2}};
//
//    private raw.commit.Grid grid1 = new raw.commit.Grid();
//
//    /**
//     * Creates new form playGame
//     */
//    public playGame() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel1 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
////        grid1Panel = new javax.swing.JPanel();
////        g1R0C2 = new javax.swing.JButton();
////        g1R0C0 = new javax.swing.JButton();
////        g1R0C1 = new javax.swing.JButton();
////        g1R1C0 = new javax.swing.JButton();
////        g1R1C1 = new javax.swing.JButton();
////        g1R1C2 = new javax.swing.JButton();
////        g1R2C1 = new javax.swing.JButton();
////        g1R2C0 = new javax.swing.JButton();
////        g1R2C2 = new javax.swing.JButton();
//        grid1.initialiseButtons();
//
//        jTextField1 = new javax.swing.JTextField();
//        jButton2 = new javax.swing.JButton();
//        grid3Panel = new javax.swing.JPanel();
//        jButton26 = new javax.swing.JButton();
//        jButton29 = new javax.swing.JButton();
//        jButton23 = new javax.swing.JButton();
//        jButton25 = new javax.swing.JButton();
//        jButton22 = new javax.swing.JButton();
//        jButton24 = new javax.swing.JButton();
//        jButton27 = new javax.swing.JButton();
//        jButton30 = new javax.swing.JButton();
//        jButton28 = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jList1 = new javax.swing.JList<>();
//        grid2Panel = new javax.swing.JPanel();
//        jButton17 = new javax.swing.JButton();
//        jButton14 = new javax.swing.JButton();
//        jButton19 = new javax.swing.JButton();
//        jButton15 = new javax.swing.JButton();
//        jButton13 = new javax.swing.JButton();
//        jButton18 = new javax.swing.JButton();
//        jButton20 = new javax.swing.JButton();
//        jButton16 = new javax.swing.JButton();
//        jButton21 = new javax.swing.JButton();
//        jButton1 = new javax.swing.JButton();
//        jLabel2 = new javax.swing.JLabel();
//        jTextField2 = new javax.swing.JTextField();
//        jLabel3 = new javax.swing.JLabel();
//        jTextField3 = new javax.swing.JTextField();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setName("Game Play"); // NOI18N
//        setResizable(false);
//
//        jPanel1.setBackground(new java.awt.Color(45, 221, 255));
//
//        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameIcons/Programming-Watch-icon.png"))); // NOI18N
//
//        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
//
////        grid1Panel.setBackground(new java.awt.Color(45, 221, 255));
//        grid1.setGridBackground();
//
////        g1R0C2.setBackground(new java.awt.Color(255, 255, 255));
////        g1R0C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R0C2.setText("C");
////
////        g1R0C0.setBackground(new java.awt.Color(255, 255, 255));
////        g1R0C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R0C0.setText("A");
////        g1R0C0.addActionListener(new java.awt.event.ActionListener() {
////            public void actionPerformed(java.awt.event.ActionEvent evt) {
////                handleTileAction(evt);
////            }
////        });
////
////        g1R0C1.setBackground(new java.awt.Color(255, 255, 255));
////        g1R0C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R0C1.setText("B");
////        g1R0C1.addActionListener(new java.awt.event.ActionListener() {
////            public void actionPerformed(java.awt.event.ActionEvent evt) {
////                handleTileAction(evt);
////            }
////        });
////
////        g1R1C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R1C0.setText("D");
////
////        g1R1C1.setBackground(new java.awt.Color(255, 255, 255));
////        g1R1C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R1C1.setText("E");
////
////        g1R1C2.setBackground(new java.awt.Color(255, 255, 255));
////        g1R1C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R1C2.setText("F");
////
////        g1R2C1.setBackground(new java.awt.Color(255, 255, 255));
////        g1R2C1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R2C1.setText("H");
////
////        g1R2C0.setBackground(new java.awt.Color(255, 255, 255));
////        g1R2C0.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R2C0.setText("G");
////
////        g1R2C2.setBackground(new java.awt.Color(255, 255, 255));
////        g1R2C2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
////        g1R2C2.setText("I");
//
//        grid1.setGridLayout();
//        grid1.generateRandomLetters();
//        grid1.populateGrid();
//
////        javax.swing.GroupLayout grid1Layout = new javax.swing.GroupLayout(grid1Panel);
////        grid1Panel.setLayout(grid1Layout);
////        grid1Layout.setHorizontalGroup(
////                grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
////                        .addGroup(grid1Layout.createSequentialGroup()
////                                .addContainerGap()
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
////                                        .addComponent(g1R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addGap(18, 18, 18)
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
////                                        .addComponent(g1R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
////                                        .addComponent(g1R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addContainerGap())
////        );
////        grid1Layout.setVerticalGroup(
////                grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
////                        .addGroup(grid1Layout.createSequentialGroup()
////                                .addContainerGap()
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
////                                        .addComponent(g1R0C0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R0C1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R0C2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addGap(18, 18, 18)
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
////                                        .addComponent(g1R1C0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R1C1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R1C2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addGap(18, 18, 18)
////                                .addGroup(grid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
////                                        .addComponent(g1R2C0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R2C1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
////                                        .addComponent(g1R2C2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
////                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
////        );
//
//        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
//        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
//        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
//
//        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
//        jButton2.setText("Add word");
//
//        grid3Panel.setBackground(new java.awt.Color(45, 221, 255));
//
//        jButton26.setBackground(new java.awt.Color(255, 255, 255));
//        jButton26.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton26.setText("T");
//
//        jButton29.setBackground(new java.awt.Color(255, 255, 255));
//        jButton29.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton29.setText("B");
//
//        jButton23.setBackground(new java.awt.Color(255, 255, 255));
//        jButton23.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton23.setText("E");
//
//        jButton25.setBackground(new java.awt.Color(255, 255, 255));
//        jButton25.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton25.setText("A");
//
//        jButton22.setBackground(new java.awt.Color(255, 255, 255));
//        jButton22.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton22.setText("S");
//
//        jButton24.setBackground(new java.awt.Color(255, 255, 255));
//        jButton24.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton24.setText("R");
//
//        jButton27.setBackground(new java.awt.Color(255, 255, 255));
//        jButton27.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton27.setText("N");
//
//        jButton30.setBackground(new java.awt.Color(255, 255, 255));
//        jButton30.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton30.setText("M");
//
//        jButton28.setBackground(new java.awt.Color(255, 255, 255));
//        jButton28.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton28.setText("U");
//
//        javax.swing.GroupLayout grid3Layout = new javax.swing.GroupLayout(grid3Panel);
//        grid3Panel.setLayout(grid3Layout);
//        grid3Layout.setHorizontalGroup(
//                grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(grid3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(grid3Layout.createSequentialGroup()
//                                                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(grid3Layout.createSequentialGroup()
//                                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(grid3Layout.createSequentialGroup()
//                                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//        grid3Layout.setVerticalGroup(
//                grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(grid3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap())
//        );
//
//        jList1.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
//        jScrollPane1.setViewportView(jList1);
//
//        grid2Panel.setBackground(new java.awt.Color(45, 221, 255));
//
//        jButton17.setBackground(new java.awt.Color(255, 255, 255));
//        jButton17.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton17.setText("F");
//
//        jButton14.setBackground(new java.awt.Color(255, 255, 255));
//        jButton14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton14.setText("K");
//
//        jButton19.setBackground(new java.awt.Color(255, 255, 255));
//        jButton19.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton19.setText("O");
//
//        jButton15.setBackground(new java.awt.Color(255, 255, 255));
//        jButton15.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton15.setText("A");
//
//        jButton13.setBackground(new java.awt.Color(255, 255, 255));
//        jButton13.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton13.setText("D");
//
//        jButton18.setBackground(new java.awt.Color(255, 255, 255));
//        jButton18.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton18.setText("E");
//
//        jButton20.setBackground(new java.awt.Color(255, 255, 255));
//        jButton20.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton20.setText("C");
//
//        jButton16.setBackground(new java.awt.Color(255, 255, 255));
//        jButton16.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton16.setText("G");
//
//        jButton21.setBackground(new java.awt.Color(255, 255, 255));
//        jButton21.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
//        jButton21.setText("C");
//
//        javax.swing.GroupLayout grid2Layout = new javax.swing.GroupLayout(grid2Panel);
//        grid2Panel.setLayout(grid2Layout);
//        grid2Layout.setHorizontalGroup(
//                grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(grid2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(grid2Layout.createSequentialGroup()
//                                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(grid2Layout.createSequentialGroup()
//                                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(grid2Layout.createSequentialGroup()
//                                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//        grid2Layout.setVerticalGroup(
//                grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(grid2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addGap(18, 18, 18)
//                                .addGroup(grid2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap())
//        );
//
//        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
//        jButton1.setText("Clear Word");
//
//        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
//        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel2.setText("CORRECT WORDS");
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
//                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                .addGap(18, 18, 18)
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(grid2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addComponent(grid3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//        jPanel2Layout.setVerticalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                                                .addComponent(grid2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                .addGap(75, 75, 75))
//                                                        .addComponent(grid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                                .addGap(145, 145, 145)
//                                                                .addComponent(grid3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                                .addGap(107, 107, 107)
//                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//
//        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
//
//        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameIcons/favourites-star-SH-icon.png"))); // NOI18N
//
//        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(26, 26, 26)
//                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(46, Short.MAX_VALUE))
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(37, 37, 37)
//                                .addComponent(jLabel1)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jLabel3)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(69, 69, 69))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                                .addGap(20, 20, 20)
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jTextField2))
//                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addGap(18, 18, 18)
//                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(48, Short.MAX_VALUE))
//        );
//
//        jLabel1.setName("countdown");
//        jLabel1.getAccessibleContext().setAccessibleName("countdownIcon");
//        jLabel1.getAccessibleContext().setAccessibleDescription("");
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//        setLocationRelativeTo(null);
//    }// </editor-fold>

    private void handleTileAction(java.awt.event.ActionEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playGame().setVisible(true);
            }
        });
    }

}
